# Generated by Django 5.0.1 on 2024-01-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0005_catalog_messagesmodel_order_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='CatalogModel',
        ),
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderModel',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewModel',
        ),
    ]
