# Generated by Django 5.0.1 on 2024-01-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0006_rename_catalog_catalogmodel_rename_order_ordermodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_lisa.catalogmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='review',
            field=models.TextField(),
        ),
    ]
