# Generated by Django 5.0.1 on 2024-01-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0007_reviewmodel_pizza_alter_reviewmodel_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogmodel',
            old_name='price_diskont',
            new_name='price_disсont',
        ),
    ]
