# Generated by Django 5.0.1 on 2024-02-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0010_remove_ordermodel_name_pizza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='count',
        ),
    ]
