# Generated by Django 5.0.1 on 2024-02-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0011_remove_ordermodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
