# Generated by Django 5.0.1 on 2024-02-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0012_ordermodel_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discont',
            field=models.IntegerField(default=0),
        ),
    ]
