# Generated by Django 5.0.1 on 2024-02-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0013_alter_user_discont'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzainorder',
            name='price_one',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
