# Generated by Django 5.0.1 on 2024-02-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0014_pizzainorder_price_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='comment',
            field=models.TextField(default='Order without Comment', null=True),
        ),
    ]
