# Generated by Django 5.0.1 on 2024-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0015_alter_ordermodel_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('COOKING', 'COOKING'), ('TASTING', 'TASTING'), ('PACKING', 'PACKING'), ('IN_DELIVERY', 'IN_DELIVERY'), ('ARCHIVE', 'ARCHIVE'), ('CANCELED', 'CANCELED')], default='NEW'),
        ),
    ]
