# Generated by Django 5.0.1 on 2024-02-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0016_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='count',
            field=models.IntegerField(),
        ),
    ]
