# Generated by Django 5.0.1 on 2024-02-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0017_alter_basketmodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='adress',
            field=models.TextField(default='self-pickup'),
        ),
    ]
