# Generated by Django 5.0.1 on 2024-02-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0019_remove_ordermodel_adress_ordermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='price_disсont',
            field=models.FloatField(default=0, null=True),
        ),
    ]
