# Generated by Django 5.0.1 on 2024-02-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0021_user_total_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total_money',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
