# Generated by Django 5.0.1 on 2024-02-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0022_ordermodel_total_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogmodel',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
