# Generated by Django 5.0.1 on 2024-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lisa', '0023_catalogmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogmodel',
            name='price_disсont',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
